---
- name: software | barrier | install flatpak
  community.general.flatpak:
    name: com.github.debauchee.barrier
  when: ansible_os_family == "Debian" and distro_codebase == "focal"

- name: software | barrier | install package
  package:
    name: barrier
  when: ansible_os_family == "Debian" and distro_codebase != "focal"
