---
- name: software | docker | add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_os_family == "Debian"

- name: software | docker | add repository ({{ distribution_codebase }})
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution_codebase }} stable"
    filename: docker
  when: ansible_os_family == "Debian"

- name: software | docker | install package (Debian-based)
  package:
    name:
      - docker-compose
      - docker.io
  notify:
    - restart docker
  when: ansible_os_family == "Debian"

- name: software | docker | install package (Archlinux-based)
  package:
    name:
      - docker-compose
      - docker
  notify:
    - restart docker
  when: ansible_os_family == "Archlinux"

- name: software | docker | create group
  group:
    name: docker

- name: software | docker | add user to group
  user:
    name: "{{ real_user }}"
    groups: docker
    append: yes
  when: real_user != "root"
