---
- name: software | docker | add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_os_family == "Debian"

- name: software | docker | add repository ({{ distribution_codebase }})
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution_codebase }} stable"
    filename: docker
  when: ansible_os_family == "Debian"

- name: software | docker | install package
  package:
    name:
      - docker-compose
      - docker.io
  when: ansible_os_family == "Debian"
