---

- import_tasks: software/misc.yml

- import_tasks: software/ansible.yml
  tags: ansible_ppa, software

- import_tasks: software/barrier.yml
  tags: packages, software

- import_tasks: software/docker.yml
  tags: dev, software

- import_tasks: software/dropbox.yml
  tags: packages, software

- import_tasks: software/git.yml
  tags: dev, software

- import_tasks: software/gitrelease.yml
  tags: dev, software

- import_tasks: software/geo.yml
  tags: network, software

- import_tasks: software/google_chrome.yml
  tags: packages, software

- import_tasks: software/homebank.yml
  tags: accounting, software

- import_tasks: software/ip4.yml
  tags: network, software

- import_tasks: software/joplin.yml
  tags: notes, software

- import_tasks: software/keepassxc.yml
  tags: packages, software

- import_tasks: software/kismet.yml
  tags: pentest, software

- import_tasks: software/media.yml
  tags: media, software

- import_tasks: software/qbittorrent.yml
  tags: packages, software

- import_tasks: software/skype.yml
  tags: packages, software

- import_tasks: software/solaar.yml
  tags: packages, software

- import_tasks: software/sublimetext.yml
  tags: packages, software

- import_tasks: software/syncthing.yml
  tags: sync, software

- import_tasks: software/ulauncher.yml
  tags: packages, software

- import_tasks: software/unetbootin.yml
  tags: packages, software
  when:
    - distro_codebase == "focal" # Currently no PPA for jammy

- import_tasks: software/veracrypt.yml
  tags: packages, software

- import_tasks: software/virtualbox.yml
  tags: vm, software

- import_tasks: software/vscode.yml
  tags: dev, software
