---

- import_tasks: software/misc.yml

- import_tasks: software/ansible.yml
  tags: software, ansible_ppa

- import_tasks: software/barrier.yml
  tags: software, packages, barrier

- import_tasks: software/docker.yml
  tags: software, dev, docker

- import_tasks: software/dropbox.yml
  tags: software, packages, dropbox

- import_tasks: software/git.yml
  tags: software, dev, git

- import_tasks: software/gitrelease.yml
  tags: software, dev

- import_tasks: software/geo.yml
  tags: software, network

- import_tasks: software/google_chrome.yml
  tags: software, packages, google_chrome

- import_tasks: software/homebank.yml
  tags: software, accounting, homebank

- import_tasks: software/ip4.yml
  tags: software, network

- import_tasks: software/joplin.yml
  tags: software, notes, joplin

- import_tasks: software/keepassxc.yml
  tags: software, packages, keepassxc

- import_tasks: software/kismet.yml
  tags: software, pentest, kismet

- import_tasks: software/media.yml
  tags: software, media

- import_tasks: software/qbittorrent.yml
  tags: software, packages, qbittorrent

- import_tasks: software/solaar.yml
  tags: software, packages, solaar

- import_tasks: software/sublimetext.yml
  tags: software, packages, sublimetext

- import_tasks: software/syncthing.yml
  tags: software, sync, syncthing

- import_tasks: software/ulauncher.yml
  tags: software, packages, ulauncher

- import_tasks: software/unetbootin.yml
  tags: software, packages, unetbootin
  when:
    - distro_codebase == "focal" # Currently no PPA for jammy

- import_tasks: software/vagrant.yml
  tags: software, vm, vagrant

- import_tasks: software/veracrypt.yml
  tags: software, packages, veracrypt

- import_tasks: software/virtualbox.yml
  tags: software, vm, virtualbox

- import_tasks: software/vscode.yml
  tags: software, dev, vscode
