---
# These are all the packages that are available directly from default repos.

- name: software | install general packages
  tags: packages, software
  package:
    name:
      - aria2
      - clusterssh
      - flameshot
      - gimp
      - git
      - gufw
      - htop
      - iftop
      - inkscape
      - inxi
      - iotop
      - ipcalc
      - jq
      - linphone
      - meld
      - ncdu
      - pavucontrol
      - pigz
      - pv
      - qpdf
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-vnc
      - tmux
      - tree
      - vim
      - vlc
      - whois

- name: software | install general apparmor packages (Debian-based)
  tags: apparmor, software
  package:
    name:
      - apparmor-utils
  when: ansible_os_family == "Debian"

- name: software | install general aws packages
  tags: aws, software
  package:
    name:
      - awscli

- name: software | install general dev packages
  tags: dev, software
  package:
    name:
      - cloc
      - git-flow
      - inotify-tools
      - lynx
      - nodejs
      - npm
      - python3-pip
      - "{{ virtualenv_package }}"

- name: software | install general gaming packages
  tags: gaming, software
  package:
    name:
      - libgtk2.0-0:i386 # pcsx2
      - lutris
      - pcsx2:i386
      - steam

- name: software | install general genealogy packages
  tags: genealogy, software
  package:
    name:
      - gir1.2-gexiv2-0.10
      - gir1.2-goocanvas-2.0
      - gir1.2-gtkspell3-3.0
      - gir1.2-osmgpsmap-1.0
      - gramps
      - graphviz
      - libgoocanvas-2.0-9
      - libgoocanvas-2.0-common
      - libgoocanvas-2.0-dev
      - libosmgpsmap-1.0-1
      - python3-pil
      - python3-pygraphviz
      - python3-svgwrite
      - sqlite3

- name: software | install general gnome packages
  tags: gnome, software
  package:
    name:
      - gnome-shell-extension-manager
      - gnome-tweaks

- name: software | install general media packages
  tags: media, software
  package:
    name:
      - audacity
      - ffmpeg
      - imagemagick
      - obs-studio
      - sox
      - vlc

- name: software | install general network packages
  tags: network, software
  package:
    name:
      - fping
      - mtr
      - ncat
      - nmap
      - proxychains
      - traceroute
      - "{{ wireshark_package }}"

- name: software | install general pentest packages
  tags: pentest, software
  package:
    name:
      - aircrack-ng
      - arp-scan
      - "{{ ettercap_package }}"
      - hashcat
      - httrack
      - hydra
      - john
      - nbtscan
      - slowhttptest

- name: software | install general pentest packages (bettercap)
  tags: pentest, software
  package:
    name:
      - bettercap
  when:
    - ansible_os_family == "Archlinux"
    - ansible_os_family == "Debian" and distro_codebase != "focal"

- name: software | install general pentest packages (Debian-specific)
  tags: pentest, software
  package:
    name:
      - dhcpig
      - hydra-gtk
  when: ansible_os_family == "Debian"

- name: software | install general ssh packages
  tags: sshd, software
  package:
    name:
      - "{{ ssh_package }}"

- name: software | install general vm packages
  tags: vm, software
  package:
    name:
      - vagrant

- name: software | configure vim
  tags: dev, software
  blockinfile:
    path: "{{ real_home }}/.vimrc"
    create: yes
    marker: '" {mark} ANSIBLE MANAGED BLOCK '
    block: "{{ vimrc }}"
