---
- name: software | virtualbox | add repository key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when: ansible_os_family == "Debian"

- name: software | virtualbox | add repository ({{ distribution_codebase }})
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ distribution_codebase }} contrib"
    filename: virtualbox
  when: ansible_os_family == "Debian"

- name: software | virtualbox | install package
  package:
    name: "{{ virtualbox_package }}"
  when: ansible_os_family == "Debian"
