# Your email address (used when setting up git).
email: ''

# Your full name (used when setting up git).
full_name: ''

# Override the Ubuntu code base for Linux Mint etc.
distribution_codebase: "{{ distro_codebase }}"

# Determine user/group details so files can be put in the right place with the right ownership.
real_user:  "{% if ansible_env['SUDO_USER'] is defined %}{{ ansible_env['SUDO_USER'] }}{% else %}{{ ansible_env['USER'] }}{% endif %}"
real_home:  "{% if real_user == 'root' %}{% if ansible_env['USER'] == 'root' %}{{ ansible_env['HOME'] }}{% else %}/root{% endif %}{% else %}{% if ansible_env['SUDO_USER'] is defined %}/home/{{ ansible_env['SUDO_USER'] }}{% else %}{{ ansible_env['HOME'] }}{% endif %}{% endif %}"
real_group: "{% if ansible_env['SUDO_GID'] is defined %}{{ ansible_env['SUDO_GID'] }}{% else %}{{ real_user }}{% endif %}"

# Public SSH keys.
public_keys:
 - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKEZRKnL68aPgv2XOw8iI+LjGbDZ3dU/0E8GcLdsyhGo vaughan.codes@gmail.com"

# IP addresses for firewall rules:
trusted_ips:
  - '192.168.0.0/25'

# Swap size (square root of RAM in GB rounded up to the nearest GB, or 1GB if the swap1 tag is present):
intended_swap_mb: "{% if 'swap1' in ansible_run_tags %}1024{% else %}{{ ((ansible_memtotal_mb / 1024) | round(0,'ceil') | root | round(0,'ceil') | int) * 1024 }}{% endif %}"

# Folders for the data partition.
data_folders:
  - Code
  - Documents
  - Downloads
  - Dropbox
  - Pictures
  - Software
  - Templates
  - Videos
  - VMs

# Vim configuration.
vimrc: |
  syntax on
  set tabstop=4
  set number
