---

- name: load variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - 'default.yml'
      paths:
        - 'vars'
  tags: always

- import_tasks: swap.yml
  tags: swap, swap1

- import_tasks: dconf-cinnamon.yml
  become_user: "{{ real_user }}"
  tags: dconf
  when: "'cinnamon' in ansible_run_tags"

- import_tasks: ufw.yml
  tags: ufw, ufw_common

- import_tasks: data.yml
  tags: data

- name: ssh | create .ssh folder
  tags: ssh
  file:
    path: "{{ real_home }}/.ssh"
    owner: "{{ real_user }}"
    group: "{{ real_group }}"
    mode: '0700'
    state: directory

- name: ssh | install public ssh key
  tags: ssh
  lineinfile:
    path: "{{ real_home }}/.ssh/authorized_keys"
    line: "{{ item }}"
    regexp: vaughan.codes@gmail.com
    owner: "{{ real_user }}"
    group: "{{ real_group }}"
    mode: '0600'
    create: yes
    backup: yes
  loop: "{{ public_keys }}"

- name: pre-software | update package cache (debian-based)
  tags: accounting, dev, devops, genealogy, network, packages, pentest, software, sshd
  apt: update_cache=yes
  changed_when: False
  when: ansible_os_family == "Debian"

- import_tasks: software/main.yml

- name: post-software | upgrade installed packages
  tags: never, upgrade
  package:
    name: "*"
    state: latest

- name: post-software | auto-download upgradable packages
  tags: upgrade
  cron:
    name: 'auto-download upgradable packages'
    minute: '42'
    hour: '0-1,8-23'
    user: root
    job: 'apt-get -dy upgrade > /var/log/apt-download-upgradable 2>&1'
    cron_file: 'apt-download-upgradable'
  notify:
    - restart cron
  when: ansible_os_family == "Debian"

- import_tasks: apparmor.yml
  tags: apparmor
