---

- name: load variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}} {{ansible_distribution_version}}.yml'
        - '{{ansible_distribution}} {{ansible_distribution_major_version}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - 'default.yml'
      paths:
        - 'vars'
  tags: always

- import_tasks: swap.yml
  tags: swap, swap1

- import_tasks: dconf-cinnamon.yml
  become_user: "{{ real_user }}"
  tags: dconf
  when: "'cinnamon' in ansible_run_tags"

- import_tasks: ufw.yml
  tags: ufw, ufw_common

- import_tasks: data.yml
  tags: data

- name: ssh | create .ssh folder
  tags: ssh
  file:
    path: "{{ real_home }}/.ssh"
    owner: "{{ real_user }}"
    group: "{{ real_group }}"
    mode: '0700'
    state: directory

- name: ssh | install public ssh key
  tags: ssh
  lineinfile:
    path: "{{ real_home }}/.ssh/authorized_keys"
    line: "{{ item }}"
    regexp: vaughan.codes@gmail.com
    owner: "{{ real_user }}"
    group: "{{ real_group }}"
    mode: '0600'
    create: yes
    backup: yes
  loop: "{{ public_keys }}"

- name: pre-software | update package cache (debian-based)
  tags: accounting, dev, genealogy, network, packages, pentest, software, sshd, vm
  apt: update_cache=yes
  changed_when: False
  when: ansible_os_family == "Debian"

- import_tasks: software/main.yml

- name: post-software | upgrade installed packages
  tags: never, upgrade
  package:
    name: "*"
    state: latest

- import_tasks: apparmor.yml
  tags: apparmor

- name: account | bash environmental variables
  tags: bash
  lineinfile:
    path: "{{ real_home }}/.bashrc"
    create: yes
    owner: "{{ real_user }}"
    group: "{{ real_group }}"
    line: 'export {{ item["name"] }}={{ item["value"] }}'
    regexp: '^\s*export {{ item["name"] }}='
  loop:
    - {'name': 'VISUAL', 'value': 'vi'}

- name: account | bash aliases
  tags: bash
  blockinfile:
    path: "{{ real_home }}/.bash_aliases"
    create: yes
    owner: "{{ real_user }}"
    group: "{{ real_group }}"
    block: |
      # Confirmation
      alias cp='cp -i'
      alias mv='mv -i'
      alias rm='rm -i'

      # Colours
      alias watch='watch --color -n1'
      alias ip='ip -c'
      alias diff='diff --color'

      # Ansible Vault
      alias avc='ansible-vault encrypt'
      alias avd='ansible-vault decrypt'
      alias ave='ansible-vault edit'
      alias avv='ansible-vault view'

      # SSH
      alias jscp='scp -o ProxyJump=jump'
      alias jssh='ssh -J jump'
      alias dssh='ssh -D 9050 jump'

      # Media
      alias ffmpeg='ffmpeg -hide_banner'
      alias ffprobe='ffprobe -hide_banner'
      alias vlc-all-audio='vlc --sout-all --sout "#display"'
